smtp:
  username: test
  password: test
  host: test
  port: 123
  sender: test
  sender_name: test

slack:
  bot_token: test

ansible:
  vault_pass: test
  remote_user: test
  home_location: test
  inventory_file: /samantha/iaac/inventory/

dialogflow:
  project_id: test
  session_id: test
  lang_code: en
  credentials_file: /samantha/dev_credentials.json

commands_settings:
  log_fetcher:
    send_via:
      - email
      - slack

    playbook_map:
      ansible: fetch-ansible-log-file.yml
